### ISSUE TITLE
请问下例子中zookeeper创建节点报了个错是什么原因，百度了下没用找到合适的解决方法

### ISSUE THREAD

**Issue by liaohanjie** [classtag/OpenRpc#2]
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /registry/data
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:114)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:786)
	at me.anduo.rpc.server.core.ServiceRegistry.createNode(ServiceRegistry.java:74)
	at me.anduo.rpc.server.core.ServiceRegistry.register(ServiceRegistry.java:44)
	at me.anduo.rpc.server.core.RpcServer.afterPropertiesSet(RpcServer.java:94)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:934)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at me.anduo.rpc.server.core.RpcBootstrap.main(RpcBootstrap.java:12)

**Comment by SilenRY** [comment]
兄弟，你的这个问题解决了吗，我也遇到了

**Comment by superxp** [comment]
兄弟，你们必须先自己去ZK创建REGISTER 目录 @liaohanjie @SilenRY

**Comment by zealrussell** [comment]
> 兄弟，你们必须先自己去ZK创建REGISTER 目录 @liaohanjie @SilenRY

兄弟，你最终运行成功了吗

**Comment by cmgyqjj** [comment]
可以通过zk控制台或者代码的方式来创建zk中的节点
这里提供控制台的方式
<img width="457" alt="image" src="https://github.com/duoan/mini-rpc/assets/47295240/5ef1b259-4272-40d2-b8b6-bb1aa34767b1">
通过`create /registry`之后再`create /registry/data`的方式创建节点
最后成功运行
<img width="1390" alt="image" src="https://github.com/duoan/mini-rpc/assets/47295240/7f5ab3de-26f4-4490-b416-92bd8032efa9">
@zealrussell

**Comment by cmgyqjj** [comment]
在RpcHandler中response默认返回error=null，但是在RpcProxy中，使用response.isError()来判断异常会导致正常执行也出错，不知道你是不是因为这个原因没有运行成功
@zealrussell
